title: Swiftx
description: Ultra-lightweight reactive UI framework
theme: jekyll-theme-minimal
url: https://morissonmaciel.github.io/swiftx
baseurl: /swiftx
markdown: kramdown
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /swiftx/
  - title: GitHub
    url: https://github.com/morissonmaciel/swiftx
